CREATE TABLE "FINOPS"."OCI_FOCUS_REPORTS"
(
  "AVAILABILITYZONE"            VARCHAR2(4000),
  "BILLEDCOST"                  NUMBER,
  "BILLINGACCOUNTID"            NUMBER,
  "BILLINGACCOUNTNAME"          VARCHAR2(32767),
  "BILLINGCURRENCY"             VARCHAR2(4000),
  "BILLINGPERIODEND"            TIMESTAMP WITH TIME ZONE,
  "BILLINGPERIODSTART"          TIMESTAMP WITH TIME ZONE,
  "CHARGECATEGORY"              VARCHAR2(4000),
  "CHARGEDESCRIPTION"           VARCHAR2(4000),
  "CHARGEFREQUENCY"             VARCHAR2(4000),
  "CHARGEPERIODEND"             TIMESTAMP WITH LOCAL TIME ZONE,
  "CHARGEPERIODSTART"           TIMESTAMP WITH LOCAL TIME ZONE,
  "CHARGESUBCATEGORY"           VARCHAR2(32767),
  "COMMITMENTDISCOUNTCATEGORY"  VARCHAR2(32767),
  "COMMITMENTDISCOUNTID"        VARCHAR2(32767),
  "COMMITMENTDISCOUNTNAME"      VARCHAR2(32767),
  "COMMITMENTDISCOUNTTYPE"      VARCHAR2(32767),
  "EFFECTIVECOST"               NUMBER,
  "INVOICEISSUER"               VARCHAR2(4000),
  "LISTCOST"                    NUMBER,
  "LISTUNITPRICE"               NUMBER,
  "PRICINGCATEGORY"             VARCHAR2(32767),
  "PRICINGQUANTITY"             NUMBER,
  "PRICINGUNIT"                 VARCHAR2(4000),
  "PROVIDER"                    VARCHAR2(4000),
  "PUBLISHER"                   VARCHAR2(4000),
  "REGION"                      VARCHAR2(4000),
  "RESOURCEID"                  VARCHAR2(4000),
  "RESOURCENAME"                VARCHAR2(32767),
  "RESOURCETYPE"                VARCHAR2(4000),
  "SERVICECATEGORY"             VARCHAR2(4000),
  "SERVICENAME"                 VARCHAR2(4000),
  "SKUID"                       VARCHAR2(4000),
  "SKUPRICEID"                  VARCHAR2(32767),
  "SUBACCOUNTID"                VARCHAR2(4000),
  "SUBACCOUNTNAME"              VARCHAR2(4000),
  "TAGS"                        VARCHAR2(32767),
  "USAGEQUANTITY"               NUMBER,
  "USAGEUNIT"                   VARCHAR2(4000),
  "OCI_REFERENCENUMBER"         VARCHAR2(4000),
  "OCI_COMPARTMENTID"           VARCHAR2(4000),
  "OCI_COMPARTMENTNAME"         VARCHAR2(4000),
  "OCI_OVERAGEFLAG"             VARCHAR2(4000),
  "OCI_UNITPRICEOVERAGE"        NUMBER,
  "OCI_BILLEDQUANTITYOVERAGE"   NUMBER,
  "OCI_COSTOVERAGE"             NUMBER,
  "OCI_ATTRIBUTEDUSAGE"         NUMBER,
  "OCI_ATTRIBUTEDCOST"          NUMBER,
  "OCI_BACKREFERENCENUMBER"     VARCHAR2(4000),
   CONSTRAINT pk_oci_finops PRIMARY KEY (
    CHARGEPERIODSTART,
    SERVICENAME,
    RESOURCEID,
    OCI_REFERENCENUMBER
  ) USING INDEX LOCAL 
 
)
PARTITION BY RANGE (CHARGEPERIODSTART)
INTERVAL (NUMTODSINTERVAL(7,'DAY'))-- Automatically creates daily partitions
(
    -- Initial partition for historical data
    PARTITION p_initial VALUES LESS THAN (TIMESTAMP'2025-01-28 00:00:00 UTC')
)
